# Generated by Django 2.2.6 on 2021-04-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datatable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=70)),
                ('Address1', models.CharField(max_length=40)),
                ('Address2', models.CharField(max_length=40)),
                ('Address3', models.CharField(max_length=40)),
            ],
        ),
    ]
